/**
 *@Generated by sagacity-quickvo 4.13
 */
package vo;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;
import vo.base.AbstractSysLocationVO;

/**
 * @project chome
 * @author jobell
 * @version 1.0.0
 * Table: sys_location,Remark:地方表 	
 */
@SqlToyEntity
public class SysLocationVO extends AbstractSysLocationVO {
	/**
	 * 
	 */
	private static final long serialVersionUID = 593012368611152965L;
	
	/** default constructor */
	public SysLocationVO() {
		super();
	}
	/*---begin-constructor-area---don't-update-this-area--*/

	/** minimal constructor */
	public SysLocationVO(Long locationId)
	{
		this.locationId=locationId;
	}

	/** full constructor */
	public SysLocationVO(Long locationId,String locationName,Long onlinePersion,Long totalPersion)
	{
		this.locationId=locationId;
		this.locationName=locationName;
		this.onlinePersion=onlinePersion;
		this.totalPersion=totalPersion;
	}

	/*---end-constructor-area---don't-update-this-area--*/
	/**
     *@todo vo columns to String
     */
    @Override
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	@Override
	public SysLocationVO clone() {
		try {
			return (SysLocationVO) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
