/**
 *@Generated by sagacity-quickvo 4.13
 */
package vo.base;

import org.sagacity.sqltoy.config.annotation.Column;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;

import java.io.Serializable;


/**
 * @project chome
 * @version 1.0.0
 * Table: sys_location,Remark:地方表  
 */
@Entity(tableName="sys_location")
public abstract class AbstractSysLocationVO implements Serializable,
	Cloneable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 4634354712557297102L;
	
	/**
	 * jdbcType:bigserial
	 * 
	 */
	@Id(strategy = "identity")
	@Column(name="location_id",length=19L,defaultValue="'sys_location_location_id_seq'",type=java.sql.Types.BIGINT,nullable=false,autoIncrement=true)
	protected Long locationId;
	
	/**
	 * jdbcType:varchar
	 * 地方名称
	 */
	@Column(name="location_name",length=200L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String locationName;
	
	/**
	 * jdbcType:int8
	 * 在线人数
	 */
	@Column(name="online_persion",length=19L,type=java.sql.Types.BIGINT,nullable=true)
	protected Long onlinePersion;
	
	/**
	 * jdbcType:int8
	 * 总人数
	 */
	@Column(name="total_persion",length=19L,type=java.sql.Types.BIGINT,nullable=true)
	protected Long totalPersion;
	

	/** default constructor */
	public AbstractSysLocationVO() {
	}
	

	/** minimal constructor */
	public AbstractSysLocationVO(Long locationId)
	{
		this.locationId=locationId;
	}

	/** full constructor */
	public AbstractSysLocationVO(Long locationId,String locationName,Long onlinePersion,Long totalPersion)
	{
		this.locationId=locationId;
		this.locationName=locationName;
		this.onlinePersion=onlinePersion;
		this.totalPersion=totalPersion;
	}
	
	/**
	 *@param locationId the locationId to set
	 */
	public AbstractSysLocationVO setLocationId(Long locationId) {
		this.locationId=locationId;
		return this;
	}
		
	/**
	 *@return the LocationId
	 */
	public Long getLocationId() {
	    return this.locationId;
	}
	
	/**
	 *@param locationName the locationName to set
	 */
	public AbstractSysLocationVO setLocationName(String locationName) {
		this.locationName=locationName;
		return this;
	}
		
	/**
	 *@return the LocationName
	 */
	public String getLocationName() {
	    return this.locationName;
	}
	
	/**
	 *@param onlinePersion the onlinePersion to set
	 */
	public AbstractSysLocationVO setOnlinePersion(Long onlinePersion) {
		this.onlinePersion=onlinePersion;
		return this;
	}
		
	/**
	 *@return the OnlinePersion
	 */
	public Long getOnlinePersion() {
	    return this.onlinePersion;
	}
	
	/**
	 *@param totalPersion the totalPersion to set
	 */
	public AbstractSysLocationVO setTotalPersion(Long totalPersion) {
		this.totalPersion=totalPersion;
		return this;
	}
		
	/**
	 *@return the TotalPersion
	 */
	public Long getTotalPersion() {
	    return this.totalPersion;
	}



	/**
     * @todo vo columns to String
     */
    @Override
	public String toString() {
		StringBuilder columnsBuffer=new StringBuilder();
		columnsBuffer.append("locationId=").append(getLocationId()).append("\n");
		columnsBuffer.append("locationName=").append(getLocationName()).append("\n");
		columnsBuffer.append("onlinePersion=").append(getOnlinePersion()).append("\n");
		columnsBuffer.append("totalPersion=").append(getTotalPersion()).append("\n");
		return columnsBuffer.toString();
	}
}
